version: "3.8"

services:
  backend:
    image: arijayat/yiphelp-backend:latest
    restart: always
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ECPIRATION: ${JWT_ECPIRATION}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    ports:
      - "3006:3006"

  frontend:
    image: arijayat/yiphelp-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3005:3005"
